development:
  adapter: postgresql
  encoding: unicode
  database: blank_template_development
  pool: 5
  username: eduardo
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: blank_template_test
  pool: 5
  username: eduardo
  password: password1
